[package]
name = "stacks"
version = "0.1.0"
edition = "2021"
description = "stacks is a service that proxies embedded databases like SQLite and DuckDB"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.8", features = ["cargo", "derive"] }
rusqlite = { version = "0.27.0", features = ["bundled"] }